variable "resource_group" {}
variable "az_region" {}
variable "vnet_name" {}
variable "environment" {}
variable "nsg_name" {}
variable "vnet_range" {}
variable "subnet_name" {}
variable "subnet_range" {}
variable "vnet1_subnets" {}