variable "resource_group" {}
variable "az_region" {}
variable "vnet_name" {}
variable "environment" {}
variable "nsg_name" {}
variable "vnet_range" {}
variable "vnet1_subnets" {}
variable "machine_size" {}
variable "admin_user" {}
variable "admin_pass" {}